# ? 1. Server Port Configuration
server.port=8084

# ? 2. Kafka Connection Properties
# Points to where your local Kafka broker cluster is running
spring.kafka.consumer.bootstrap-servers=localhost:9092
# A unique group identity for your Notification consumers
spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# ? 4. JSON Security Mapping
# Tells Spring to trust and unpack incoming event classes from your project packages
spring.kafka.consumer.properties.spring.json.trusted.packages=com.vijayshopee.*

# ? 5. JavaMail SMTP Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saurabhmoreals4@gmail.com
spring.mail.password=mfxgvchbujtqvqsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true