services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 🗄️ MySQL Database Service
  mysql-db:
    image: mysql:8.0
    container_name: vijayshopee-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Saurabh@123"
      MYSQL_DATABASE: "vijayshopee_auth_db"
    volumes:
      - mysql_data:/var/lib/mysql

  api-gateway:
    build: ./api-gateway
    image: saurabh632000/vijayshopee-api-gateway:latest
    container_name: vijayshopee-api-gateway
    ports:
      - "8060:8060"
    environment:
      - SERVER_PORT=8060
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

  auth-service:
    build: ./auth-service
    image: saurabh632000/vijayshopee-auth-service:latest
    container_name: vijayshopee-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8081
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

  product-service:
    build: ./product-service
    image: saurabh632000/vijayshopee-product-service:latest
    container_name: vijayshopee-product-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8082
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

  order-service:
    build: ./order-service
    image: saurabh632000/vijayshopee-order-service:latest
    container_name: vijayshopee-order-service
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8083
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

  notification-service:
    build: ./notification-service
    image: saurabh632000/vijayshopee-notification-service:latest
    container_name: vijayshopee-notification-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=8084
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:29092

  payment-service:
    build: ./payment-service
    image: saurabh632000/vijayshopee-payment-service:latest
    container_name: vijayshopee-payment-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8085
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

  shipping-service:
    build: ./shipping-service
    image: saurabh632000/vijayshopee-shipping-service:latest
    container_name: vijayshopee-shipping-service
    ports:
      - "8086:8086"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8086
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_shipping_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

  inventory-service:
    build: ./inventory-service
    image: saurabh632000/vijayshopee-inventory-service:latest
    container_name: vijayshopee-inventory-service
    ports:
      - "8087:8087"
    depends_on:
      - kafka
      - mysql-db
    environment:
      - SERVER_PORT=8087
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/vijayshopee_inventory_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Saurabh@123

# 📂 Global volume declaration
volumes:
  mysql_data: